pkg/system/xattr_linux.go

On RHEL/Fedora this fixes issues under SELinux where trying to remove a
"security.selinux" label is a capital-B bad idea. It also might be
necessary to handle blacklisting "security.*" xattrs when we generate
archives.
Fixes: cyphar/umoci#49

pkg: xattr: ignore EPERM in Lclearxattrs

---

README.md

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

README.md: fix links and formatting

---

CHANGELOG.md

CHANGELOG: update to include recent changes

---

packaging/suse/.gitignore
packaging/suse/make_spec.sh

Signed-off-by: Maximilian Meister <mmeister@suse.de>

packaging: add packaging helper to automate submissions to obs

---

oci/config/convert/runtime.go

oci: config: also make exposedPorts an annotation

---

CHANGELOG.md
README.md

*.md: various cleanups

---

contrib/pkg/suse/make_spec.sh

Signed-off-by: Maximilian Meister <mmeister@suse.de>

packaging: make branch configurable

---

CHANGELOG.md

CHANGELOG: update to include OCI update

---

Dockerfile

dockerfile: update to skopeo v0.1.23

---

CHANGELOG.md
contrib/pkg/suse/make_spec.sh
hack/release.sh

release: fix broken $gpgflags

---

CHANGELOG.md

CHANGELOG: mention pr157

---

hack/release.sh

This is so that other projects (such as runc) can use our release script
with minimal changes (and the changes can be contained to just the top
portion of the script, making updating easier).

release: make script more generic

---

CHANGELOG.md

CHANGELOG: update release mention [ci skip]

---

CHANGELOG.md

CHANGELOG: fix mistakes

---

CHANGELOG.md
oci/layer/tar_extract.go
test/repack.bats

*: fix xattr inconsistency issue

---

doc/site/_index.md
doc/site/quick-start/garbage-collection.md

doc/site: fix a couple more typos

---

Makefile

Re-do of #203. As discussed there, there are outstanding SELinux issues with the tests even if we avoid the labelling one.
With the current Makefile, the Docker variants of the tests don't work
out of the box on SELinux-enabled systems because the volume mount
(namely, the source directory) isn't labelled correctly. This patch
simply disables SELinux labelling for these particular containers,
as the easiest way to mitigate this issue. (This seems preferable to
using the `:z` or `:Z` option to the Docker volume mount, which would
forceably relabel the directory every time the Docker command is run.)

Makefile: disable SELinux for tests in Docker

---

cmd/umoci/tag.go
doc/man/umoci-list.1.md

List is an action on a layout, not an image.
Signed-off-by: Serge Hallyn <shallyn@cisco.com>

fix help message for 'list'

---

oci/layer/unpack.go

Layers can be stored in tar format alone, so let's not force gunzip.

don't always gunzip layers

---

README.md
doc/site/quick-start/rootless.md

*: doc fixups

---

oci/layer/unpack.go

Port over moby/moby#35205
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
- - -
Without this, the mount fails EPERM on Ubuntu.

rootless: keep CL_UNPRIVILEGED "locked" flags for bind-mounting resolv.conf

---

README.md

Signed-off-by: Abhilash Raj <raj.abhilash1@gmail.com>
Another version of #241

Update quickstart URL to point to website.

---

CHANGELOG.md

CHANGELOG: update to include Tycho's changes

---

README.md

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

fix code path.

---

hack/test-vendor.sh

It turns out that vendor/modules.txt changes its contents seemingly at
random, and so there's no point including it in our comparison
(especially since it's not used to build anything).

hack: ignore vendor/modules.txt when comparing

---

pkg/unpriv/unpriv_utimes_test.go

clean up some test dirs

---

cmd/umoci/new.go
cmd/umoci/raw-unpack.go
cmd/umoci/repack.go
cmd/umoci/unpack.go
new.go
repack.go
unpack.go

We'd like to use mostly the same code from some of the umoci commands, so let's make them available from some form of "API".

Hoist api functions

---

CHANGELOG.md

CHANGELOG: update with new developments

---

MAINTAINERS

MAINTAINERS: add tych0

---

mutate/mutate.go
mutate/mutate_test.go

in order to add layers that may already exist in the image to a mutator, we
would previously have to read the layer off the disk, decompress it, and
recompress it (arriving at the same results, modulo gzip stream weirdness).
Let's instead just implement an API for letting us do this directly,
without all the i/o and CPU usage.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
I somehow can't run the CI locally:
```
#6 ERROR: executor failed running [/bin/sh -c zypper mr -d repo-non-oss repo-update-non-oss && 	zypper ar -f -p 5 -g obs://home:cyphar:bats obs-bats && 	zypper ar -f -p 10 -g obs://Virtualization:containers obs-vc && 	zypper ar -f -p 10 -g obs://devel:tools obs-tools && 	zypper ar -f -p 10 -g obs://devel:languages:go obs-go && 	zypper --gpg-auto-import-keys -n ref && 	zypper -n …
```

mutate: implement an AddExisting() API

---

.github/dependabot.yml

gha: enable dependabot
