opencontainers/umoci

- .lgtm
This uses [lgtmco/lgtm][1] which is a free software LGTM approval service,
which is currently discontinued but I will spin up a service for my own
repos.
Since I'm currently the only maintainer, I have to allow self-approvals
and also only require one LGTM.
[1]: https://github.com/lgtmco/lgtm
> lgtm: add lgtm approval

- fseval.go
- fseval_default.go
- fseval_rootless.go
- oci/layer/tar_extract.go
- pkg/unpriv/unpriv.go
- test/repack.bats
This also includes the change to unpriv, so that we can do unprivileged
Mknod creation. Currently I haven't put the hacks done for devices
because that code is quite frankly pretty dark.
> fseval: add Mknod

- Dockerfile
- cmd/umoci/repack.go
- cmd/umoci/unpack.go
- cmd/umoci/utils.go
- fseval.go
- fseval_default.go
- fseval_rootless.go
- hack/gomtree-0001-compare-always-diff-xattr-keys.patch
- hack/gomtree-0001-keywords-encode-xattr.-keywords-with-Vis.patch
- hack/patch.sh
- oci/layer/tar_extract.go
- oci/layer/tar_generate.go
- pkg/unpriv/unpriv.go
- test/repack.bats
- vendor/github.com/vbatts/go-mtree/compare.go
- vendor/github.com/vbatts/go-mtree/keywords_linux.go
This implements xattr handling in tar_generate, as well as some other
cleanups.
By necessity we have to ignore some xattrs (such as security.selinux),
but hopefully this is a rare case of things we need to ignore -- I don't
really want to have to maintain a set of xattrs that are and are not
safe to handle.
Fixes: cyphar/umoci#52
> oci: layer: add xattrs to new layers

- cmd/umoci/main.go
We still need to massively reduce the amount of dumb output we are
spewing out. Logrus is both a blessing and a curse.
Reported-by: Antonio Murdaca <runcom@redhat.com>
> cmd: give 'helpful' hint about --rootless

- oci/cas/cas.go
- oci/cas/dir.go
- oci/cas/dir_test.go
- oci/cas/gc.go
- pkg/system/lock_linux.go
- test/gc.bats
This adds support for cleaning of dead temporary directories inside
an OCI layout directory. It's all implemented using locking.
Fixes #17 
> gc: clean internal directories

- Makefile
The old setup didn't actually statically compile umoci, so we have to
add CGO_ENABLED=0 in order to make the damn thing static. Also,
installing dependencies is a bad idea.
> Makefile: fix static compilation

- Makefile
- oci/cas/dir_test.go
- oci/layer/tar_extract_test.go
This is necessary for %check-style testing inside the openSUSE RPMs, so
that we can make sure that everything works (or appears to work) when
releasing packages. This is done by making local-unit-tests work as
non-root.
It also increases unit test coverage for the rootless case.
> *: make unit tests more %check-friendly

- Makefile
- cmd/umoci/main_test.go
- hack/test-integration.sh
- hack/test-unit.sh
- test/helpers.bash
This makes the hack/test-* scripts work in a non-coverage mode that
allows users to run hack/test-integration with a regular umoci binary.
> *: make coverage optional

- hack/test-unit.sh
- third_party/user/user_test.go
The test code apparently breaks on i596, fix it by not using strconv
anymore.
> third_party: user: fix 32-bit build

- CHANGELOG.md
Add full changelog to CHANGELOG.md, which is much better for handling
the changelog than adding everything to tags which aren't as in-band as
a file in the repo.
> *: add CHANGELOG

- CHANGELOG.md
- cmd/umoci/tag.go
- test/tag.bats
Previously, tags would always be clobbered, but this logic was subtly
broken for "umoci tag". Fix this by matching the other PutReference
usages.
Ensure that we don't get a regression for "umoci tag" clobbering.
Fixes: 8b73b49 ("*: make logging [log.Info] much more user-friendly")
> cmd/umoci: tag: fix tag clobbering

- Makefile
Stop creating useless files inside the source directory when not doing a
full coverage run of tests.
Carry of #77.
> makefile: fix temporary coverage files

- cmd/umoci/config.go
- cmd/umoci/new.go
- cmd/umoci/repack.go
- cmd/umoci/stat.go
- cmd/umoci/unpack.go
- cmd/umoci/utils.go
- mutate/mutate.go
- oci/cas/blob.go
- oci/cas/cas.go
- oci/cas/cas_test.go
- oci/cas/dir.go
- oci/cas/dir_test.go
- oci/cas/gc.go
- oci/layer/unpack.go
The previous API didn't make much sense, and was quite confusing when
actually trying to use it (nil would always cause errors, and the
intention of the call is not to modify the arguments).
This is part of the preparation of putting oci/cas into an OCI
repository.
> oci: cas: *ispec.Descriptor -> ispec.Descriptor

- Makefile
- README.md
Here's a few makefile targets/refactors to support a `make install` target. PTAL.
Fixes #99
> Install target

- CHANGELOG.md
- Makefile
- contrib/pkg/suse/make_spec.sh
The version parsing was broken in e4f29ed51033 ("packaging: move to
contrib/pkg"). Also add an entry to the CHANGELOG.
It appears this broke openSUSE's build setup. Since my local developer
environment no longer relies on super-dodgy symlinks I don't mind being
explicit.
> contrib: pkg: fix make_spec version

- test/config.bats
- test/create.bats
- test/gc.bats
- test/helpers.bash
- test/pack_mapping.bats
- test/repack.bats
- test/stat.bats
- test/tag.bats
- test/unpack.bats
Previously we dropped bundle cleanups because rm(1) is not sophisticated
enough to know how to remove rootless rootfs-es. But this causes issues
with Travis (which has a cap on root filesystem size) so hack around the
rm(1) issues with a chmod 0777 -- which hopefully should handle all of
the important cases.
We have to track everything created with setup_testdir in a separate
manifest file because it turns out that global variables are hard to
modify in bash.
Closes #105 
> test: clean up bundles in tests

- CHANGELOG.md
- cmd/umoci/config.go
- man/umoci-config.1.md
- test/config.bats
While the current UX for --config.cmd and --config.entrypoint seems odd
(since they aren't treated atomically, which doesn't make any sense).
But since we're currently treating them like ENV we need to provide a
way to explicitly clear them (even though we clear the old value when
creating a new one).
Reported-by: David Cassany <dcassany@suse.com>
> cmd: add support for --clear=config.{cmd,entrypoint}

- README.md
Plus for those copying and pasting, if their `$GOPATH` is not `$HOME`
then they will not have to edit that line before pasting.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> README: reuse the variable for install

- CHANGELOG.md
- oci/layer/unpack.go
- test/config.bats
We can't join any additional groups as an unprivileged user, so
retaining these groups will always cause failures.
I found this while working on cyphar/orca-build#6.
> unpack: don't set AdditionalGids in rootless mode

- CHANGELOG.md
- cmd/umoci/main.go
- cmd/umoci/raw-runtime-config.go
- cmd/umoci/raw.go
- cmd/umoci/utils_ux.go
- man/umoci-config.1.md
- man/umoci-ls.1
- man/umoci-ls.1.md
- man/umoci-raw-config.1.md
- man/umoci-raw-runtime-config.1.md
- man/umoci-raw.1.md
- man/umoci-rm.1
- man/umoci-rm.1.md
- man/umoci.1.md
- oci/config/convert/runtime.go
- oci/layer/unpack.go
- test/help.bats
- test/raw-config.bats
Add a new command to allows users that have to parse the generated
config.json often much more efficient (by allowing them to skip the
layer unpacking steps).
Since the output of this command is not quite obvious unless you know
what it's doing, hide it behind a "raw" subcommand that should scare
away users that don't know enough about the OCI specs.
Implements #21
> cmd: umoci: add umoci-raw-runtime-config(1)

- CHANGELOG.md
- Dockerfile
- Makefile
- hack/patch.sh
- hack/runtime-tools-0001-generate-remove-validate-dependency.patch
- hack/vendor.sh
- oci/config/convert/runtime.go
- oci/layer/tar_extract_test.go
- oci/layer/unpack.go
- oci/layer/utils.go
- pkg/idtools/idtools.go
- pkg/idtools/idtools_test.go
- test/raw-config.bats
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_action.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_architecture.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_arguments.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_remove.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/syscall_compare.go
- vendor/github.com/opencontainers/runtime-tools/generate/spec.go
The most recent runC version requires v1.0.0-rc5, which requires some
changes. In addition, runtime-tools needed to be updated. This patch
updates the following vendors:
* github.com/opencontainers/runtime-spec@v1.0.0-rc5
+ runtime-tools-0001-generate-remove-validate-dependency.patch
* github.com/opencontainers/runtime-tools@b081a428c91705169ec3628a10bd5ca9992afea9
This also contains the trivial changes to the names of various types.
Fixes #113
> vendor: update to runtime-spec@v1.0.0-rc5

- CHANGELOG.md
- Makefile
- hack/release.sh
Rather than doing all releases manually, write some scripts to generate
everything. In addition, generate signed archives of the source code for
easier downloading of verified source code.
> *: add 'make release' scripts

- oci/cas/drivers/dir/dir.go
The error messages should be negated to express the error.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> drivers/dir: validate: correct error messages

- oci/config/convert/runtime.go
- oci/layer/unpack.go
- test/config.bats
- test/raw-config.bats
- third_party/user/user.go
Extend the config generation to match the conversion spec described in [opencontainers/image-spec](https://github.com/opencontainers/image-spec/pull/492) as requested in #119.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> generate: match spec conversion

- CHANGELOG.md
This stuff comes from #121 and #120, which I forgot to ask
@vrothberg to add to the `CHANGELOG.md`.
> CHANGELOG: add stuff from @vrothberg

- oci/config/convert/runtime.go
- oci/config/generate/spec.go
Move it to the API to avoid potential code duplication and make it reusable, as discussed in #120.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> generate: get string array of exposed ports

- .travis.yml
- Makefile
This recently broke on Travis, and it appears that there's some
mysterious permission issue happening with the interactions between
Docker and the coverage file.
Really we should make the CI not use Docker at all, but the package
requirements are forcing us to use CI for now. Hopefully we can improve
this in the future.
> ci: fix EPERM coverage file

- cmd/umoci/config.go
- oci/config/generate/spec.go
Add clear API for config.cmd and config.entrypoint to make the API more
consistent.
> Generator: make clear API consistent

- .travis.yml
- Makefile
- hack/release.sh
Add a new target local-validate-reproducible which will verify that our
builds remain reproducible even if you rebuild them within 10s of each
other and the modified time of the source code is changed. This is a
very trivial way of checking reproducibility, but Go makes guarantees
that the binaries are always reproducible[1].
[1]: https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/
> make: add validation for reproducibility

- CHANGELOG.md
- cmd/umoci/repack.go
- pkg/mtreefilter/mask.go
- pkg/mtreefilter/mask_test.go
- test/repack.bats
This is (unfortunately) not mandated in [the][1] [specification][2], but in
order to avoid accidentally spilling private information into published
layers (which is one use of Volumes) we must ignore all layers included
in Config.Volumes.
In future we should also add some flags or alernative ways of masking
paths.
[1]: opencontainers/image-spec#496
[2]: opencontainers/image-spec#504
> repack: do not include Volume paths in new layers

- CHANGELOG.md
- Dockerfile
- hack/patch.sh
- hack/runtime-tools-0002-generate-fix-build-for-v1.0.0.patch
- hack/vendor.sh
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
On paper this change should not affect anything, but we needed to add a
patch in order to fix a late change in runtime-spec that broke the
runtime-tools/generate build.
> *: update to v1.0.0 of {runtime,image}-spec

- .travis.yml
- CHANGELOG.md
- Makefile
- cmd/umoci/config.go
- cmd/umoci/gc.go
- cmd/umoci/new.go
- cmd/umoci/raw-runtime-config.go
- cmd/umoci/repack.go
- cmd/umoci/stat.go
- cmd/umoci/tag.go
- cmd/umoci/unpack.go
- mutate/mutate.go
- mutate/mutate_test.go
- oci/casext/casext.go
- oci/casext/json_dir_test.go
- oci/casext/refname_dir_test.go
- oci/layer/unpack.go
- pkg/mtreefilter/mask_test.go
It appears that local-validate has not been running in recent PRs. Fix
this by reworking `make ci` and the travis configuration to make sure it
runs. This is critical for CII bading.
In addition, this un-comments git-validation which has resolved their
issues with running in Travis.
> 	*: rework validation scripts

- doc/security.md
This adds a document that describes the current security considerations
and trade-offs made within umoci. It is not a complete document (and two
of the three issues have yet to be satisfactorily addressed) but it
helps users understand what the current situation is (as well as
providing some information to potential contributors).
> doc: add security considerations

- CHANGELOG.md
- cmd/umoci/unpack.go
- doc/man/umoci-unpack.1.md
- pkg/idtools/idtools.go
- pkg/idtools/idtools_test.go
- test/pack_mapping.bats
Our IDMap interfaces were not matching what a user who is familiar with
user_namespaces(7) would expect. This caused me some confusion while
trying to debug a user namespace bug. While this is a breaking change,
I'm fairly confident that there are almost no users of this feature.
In addition, actually add documentation on the --[ug]id-map format
(which was previously not explicitly documented at all).
Fixes: 9f88dd9 ("{un,re}pack: implement ID mapping")
> repack: change --[ug]id-map= UX to match user_namespaces(7)

- CHANGELOG.md
- oci/layer/tar_extract.go
- test/unpack.bats
On Linux, as a security feature, setuid flags are dropped when a file
owner is changed. As a result, our previous implementation would not
correctly preserve setuid bits on binaries. Fix this by swapping the
order.
Fixes #166
> oci: tar: apply chmod after chown to preserve setuid flags

- cmd/umoci/config.go
Fixes a panic when an argument to `--config.label` is badly formed
(e.g. doesn't contain an equals sign).
> cmd: add check for bad label strings

- CHANGELOG.md
- oci/layer/unpack.go
Different tar implementations can have different levels of redundant
padding and other similar weird behaviours. While on paper they are all
entirely valid archives, Go's tar.Reader implementation doesn't
guarantee that the entire stream will be consumed (which can result in
the later diff_id check failing because the digester didn't get the
whole uncompressed stream). Just blindly consume anything left in the
layer.
Reported-by: "Serge E. Hallyn" <serge@hallyn.com>
> oci: consume any excess data present in layer archives

- CHANGELOG.md
- doc/security.md
- oci/layer/unpack.go
This protects against attacks where an unsafe image is extracted into a
location where an unprivileged user could potentially access unsafe
setuid binaries (or unsafe inodes). This protection is very easy to
disable by a user of umoci, but the intention is to protect against
lowest-common-denominator attacks.
This is a slightly breaking change, but as it is a security issue (which
was previously documented) we have made the change anyway.
Fixes #181
> layer: always set bundle to 0700 on creation

- CHANGELOG.md
- oci/layer/unpack.go
In order to ensure we don't leave around a broken bundle directory,
remove the bundle if a failure occurred. While cleaning up isn't a huge
issue for unpacking as root, cleaning up as an unprivileged user gets
quite complicated ("rm -rf" doesn't work).
Fixes #174 
Reported-by: "Serge E. Hallyn" <serge@hallyn.com>
/cc @hallyn
> unpack: cleanup bundle in case of failure

- cmd/umoci/unpack.go
previously, nonexistent tags were confusingly reported as being
ambiguous.
Signed-off-by: Serge Hallyn <serge@hallyn.com>
> unpack: detect nonexistent tag [trivial]

- CONTRIBUTING.md
The link for "create pull request" is missing, add it.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> CONTRIBUTING: add missing reference link

- cmd/umoci/utils.go
As of 731b4c57bfb72c5e75ee625b6d7bae3ac23dcd87 `--from` no longer exists.
> cmd: fix argument name in comment

- CHANGELOG.md
- cmd/umoci/repack.go
- cmd/umoci/unpack.go
- cmd/umoci/utils.go
- doc/man/umoci-repack.1.md
- test/repack.bats
When this flag is supplied, umoci will refresh the bundle's metadata
(namely, the mtree manifest and the umoci metadata JSON) to record the
state of the bundle when the repack is performed. This means that an
unpack immediately after a repack should be essentially idempotent.
Fixes #196
> umoci/repack: add `--refresh-bundle` flag

- test/repack.bats
Looks like I missed this on first-pass. This test didn't check that
umoci-repack succeeded in one of the cases. Add the corrected checks to
match the rest of the testing suite.
> test: correct test for --refresh-bundle

- oci/layer/generate.go
- test/helpers.bash
- test/repack.bats
There were various references to patched versions of go-mtree, but all
mentioned fixes are now in the upstream version that umoci is using.
> *: clean some old deprecated comments

- Makefile
- hack/test-integration.sh
Running all the integration tests can be a bit tedious when a developer
is iterating on a particular subcommand. This adds the ability to
specify a subset of tests by passing the `TESTS=` argument to the
`test-integration` and `local-test-integration` Make targets. This
argument expects the name of one or more tests, each of which is
expected to match a .bats file in the `tests/` directory. If unset, we
continue to default to running all tests.
Examples:
$ make TESTS="gc" test-integration
$ make TESTS="unpack repack" local-test-integration
$ make test-integration
> Makefile: add option to specify individual test(s)

- Dockerfile
- test/create.bats
- test/helpers.bash
As of
https://github.com/opencontainers/image-tools/commit/1423c5e01935372d9f069e158f11a0f1b43df221,
oci-image-tools moved the individual commands into subcommands (i.e.
`oci-image-validate` became `oci-image-tool validate`. The umoci
development Dockerfile installs a very old version of the OCI image
tools [1][1] before this merge happened; and although it installs a
specific (newer) version of the image tools "over the top" [2][2],
during the tests we were specifically calling `oci-image-validate` which
would invoke the old version.
[1]: https://github.com/openSUSE/umoci/blob/80f8d32c23772c3d9f20d02f82fd6a60186c0e92/Dockerfile#L35
[2]: https://github.com/openSUSE/umoci/blob/80f8d32c23772c3d9f20d02f82fd6a60186c0e92/Dockerfile#L67
> test: change oci-image-validate reference

- .travis.yml
- Dockerfile
Remove un-used OBS projects from Dockerfile, as well as updating the
version of the openSUSE image we test.
> ci: small fixes

- cmd/umoci/config.go
- cmd/umoci/raw-runtime-config.go
- cmd/umoci/stat.go
- cmd/umoci/tag.go
- oci/casext/gc.go
Previously, nonexistent tags were confusingly reported as being
ambiguous.
Commit 09c6ab38 only handled one instance, catch the rest.
Signed-off-by: Serge Hallyn <serge@hallyn.com>
> detect nonexistent tag

- CHANGELOG.md
- oci/cas/dir/dir.go
- oci/cas/dir/dir_test.go
Following Git and [defaulting to two weeks][1], as discussed in #17.  This allows the use of other non-flocking consumers (e.g. other CAS implementations) in the same base directory.
The added robustness comes with a price, though, since we now have to balance cleanliness vs. robustness for those other consumers.
* The hard-coded two-week cutoff may be insufficient for some use cases.  Maybe somebody will need to download a huge layer through a very slow pipe, and they'll bump into this limit.  Or maybe they have a high-cruft workflow or a small disk and would like to shorten this limit.  If that happens or we become concerned that it might, we should make `pruneExpire` configurable.
* Increasing `pruneExpire` protects more flock-less consumers from `Clean`, but also means that cruft can …
> oci/cas/dir: Only Clean .umoci-* directories

- doc/site/quick-start/rootless.md
- oci/layer/tar_extract.go
It appears that golang.org/x/sys/unix doesn't add path information to
errors (and only return the syscall.Errno). While this is fine, it
caused rootless warnings to be needlessly confusing. In addition, the
warnings looked too scary before. Hopefully they seem less worrying now.
In addition, add a new warning when we fake a device inode. Most of the
container images I've tested don't appear to contain them, so the
warning isn't too spammy (and also it doesn't look as worrying
hopefully).
/cc @davidcassany 
>  layer: improve warnings in rootless mode

- oci/cas/cas.go
- oci/casext/blob.go
- oci/casext/walk.go
This is to make our handling of OCI extensions much nicer when walking
over blobs.
Replacement for #104.
> oci: walk: ignore unknown mediatypes

- CHANGELOG.md
- oci/layer/tar_extract.go
- test/repack.bats
In order to work around cases where we are replacing a file we don't
have write access to in unprivileged mode (as well as to clarify the
hardlink semantics of unpacking), always remove the target path (unless
it's a directory) before unpacking over it. As we always re-apply
metadata this should not cause any issues.
Fixes #222
> oci: tar extract: remove non-dir targets on unpack

- Makefile
- hack/ci-coverage.sh
- oci/casext/refname.go
- oci/layer/tar_unix.go
- pkg/system/mknod_linux_test.go
In order to avoid the CI from slowly becoming less and less reliable,
enforce a hard coverage cutoff for the entire project. 80% should be
good enough for the moment.
Closes #154 
> ci: make test coverage have a cutoff

- CHANGELOG.md
- oci/layer/tar_extract.go
- oci/layer/tar_extract_test.go
- oci/layer/tar_generate.go
- pkg/fseval/fseval.go
- pkg/fseval/fseval_default.go
- pkg/fseval/fseval_rootless.go
- pkg/unpriv/unpriv.go
- pkg/unpriv/unpriv_test.go
- test/repack.bats
Add full opaque whiteout support, including the handling of new files
present in the upper layer (and thus should not be removed). The code
implementing this is fairly fragile and has to deal with a lot of really
annoying edge cases, so many new tests were added for this portion.
There are a few semantics differences found between unpriv.Walk and
filepath.Walk by this patch (especially when it comes to handling ENOENT
during the walk). These semantics have been fixed in the WalkFunc used,
but probably deserve a refactor in future.
Closes #224 
> oci: tar extract: full opaque whiteout support

- CHANGELOG.md
- oci/layer/tar_extract.go
- third_party/shared/COPYING
- third_party/shared/util.go
Some rootless tricks we do (such as faking block devices) are useful in
user namespaces, while others (ignoring Lchown) are not. In the future
the way we handle this will probably change (especially with the advent
of seccomp-userspace traps which would allow for mknod(2) emulation in
userspace -- removing the privilege problem), but currently we enable
some tricks if we are detected as being in a user namespace.
It should be noted that user namespace checks are very fickle. There
isn't any way to guarantee you are not in a user namespace without
trying something like mknod(2) and noticing it fails when it shouldn't
(and even that could be blocked by other things). So the check we do
(see if /proc/self/uid_map has the same value as the root user
namespace) is 99% accurate though it can be …
> oci: tar extract: enable some rootless tricks in user namespace

- CHANGELOG.md
- oci/layer/tar_extract.go
- oci/layer/tar_extract_test.go
08da5c6d0fd9 ("oci: tar extract: full opaque whiteout support") added
handling for opaque whiteouts such that out-of-order whiteouts were
still handled correctly. However, this new handling wasn't extended to
regular whiteouts (which have effectively the same semantics).
Correct this by refactoring out the removal function we crafted for
opaque whiteouts and just use it for all whiteouts.
Closes #224 (again).
> oci: tar extract: handle out-of-order regular whiteouts

- CHANGELOG.md
- cmd/umoci/tag.go
- cmd/umoci/utils_ux.go
- oci/casext/refname.go
- oci/casext/refname_test.go
Previously we only supported a very limited subset of reference names
(as per the specification), but the restrictions have been expanded to
allow for any reference of the form
refname   ::= component ("/" component)*
component ::= alphanum (separator alphanum)*
alphanum  ::= [A-Za-z0-9]+
separator ::= [-._:@+] | "--"
Add support for this newly expanded set of reference names. In addition,
refactor the checks for whether a reference name is valid.
> oci: casext: extend scope of valid reference names

- cmd/umoci/raw-runtime-config.go
- cmd/umoci/unpack.go
- cmd/umoci/utils.go
- cmd/umoci/utils_ux.go
- doc/man/umoci-raw-runtime-config.1.md
> Refactor ID mapping

- test/helpers.bash
- test/repack.bats
Apparenty Fedora has made some of their binaries unwriteable for all
users, which results in the rootless tests failing with strange errors:
not ok 60 umoci repack [replace]
Fix this by just forcing removal everywhere in the tests.
> test: force removal to fix Travis CI failure

- Makefile
- cmd/umoci/insert.go
- cmd/umoci/main.go
- oci/layer/generate.go
- oci/layer/tar_generate.go
- test/insert.bats
There are cases where you only want to insert files into an image. Right
now the procedure is: unpack the image, add the files, and repack the
image. However, the OCI format lends itself exactly to this kind of
addition -- we can just add a new layer with the files we wish to insert.
Additional motivation is in the case of large layers, we can avoid a lot of
i/o, CPU time to compress, and disk space requirements.
So, let's add a command to generate this new import layer.
> add `umoci insert` command

- CHANGELOG.md
- cmd/umoci/raw-unpack.go
- cmd/umoci/raw.go
- doc/man/umoci-raw-unpack.1.md
- oci/layer/unpack.go
- test/helpers.bash
- test/raw-unpack.bats
This is pretty basic, and duplicates quite some code with the existing `unpack` code, that's why I've tagged this as WIP, to get the ball going and discuss our options.
I would like this feature for cases where we only care about getting the final rootfs. Computation of the mtree file can take a significant amount of time on large images (because of all the checksums that need to be computed).
thoughts @cyphar?
Closes #23
> umoci: add "raw unpack"

- README.md
- api.go
- api_test.go
They were missing and it's probably a good idea to include them, purely
to make legal review less of a pain.
/cc @tych0 
> *: add cisco copyright line in new files

- Dockerfile
- cmd/umoci/raw-add-layer.go
- cmd/umoci/raw.go
- doc/man/umoci-insert.1.md
- doc/man/umoci-raw-add-layer.1.md
- doc/man/umoci-unpack.1.md
- oci/layer/tar_extract.go
- oci/layer/tar_extract_test.go
- oci/layer/utils.go
- test/config.bats
- test/create.bats
- test/gc.bats
- test/help.bats
- test/helpers.bash
- test/insert.bats
- test/pack_mapping.bats
- test/raw-add-layer.bats
- test/raw-config.bats
- test/raw-unpack.bats
- test/repack.bats
- test/stat.bats
- test/tag.bats
- test/unpack.bats
- vendor.conf
- vendor/github.com/cyphar/filepath-securejoin/join.go
This is a very simple helper function that allows users to "BYO" layers
that were generated elsewhere. It should be noted that this does
slightly hardcode tar archives into umoci's interface more than I'd
like, but I'm sure we can work around that if we have to in the future.
In addition, this fixes the --keep-dirlinks tests to test all of the
important features (like nesting resolution as well as loop detection
and breakout).
/cc @tych0
> cmd: add 'umoci raw add-layer'

- CHANGELOG.md
- cmd/umoci/insert.go
- cmd/umoci/repack.go
- doc/man/umoci-insert.1.md
- oci/layer/generate.go
- oci/layer/tar_generate.go
- pkg/mtreefilter/mask.go
- pkg/mtreefilter/mask_test.go
- test/insert.bats
Previously umoci-insert(1) was quite limited in that it would only
insert a given file or directory without having any configurability.
Something users might want is the ability to delete a path without an
unpack-repack cycle. Or they want to replace the contents of a directory
rather than merge them.
To this effect, add --whiteout and --opaque which provide the
corresponding features. --whiteout just adds a whiteout at the target
path, while --opaque adds an opaque whiteout for the target before doing
the copy.
In addition, add support for "simplified whiteouts". This change ultimately
makes our images a little bit smaller by no longer whiting-out every sub-entry
when a directory has been deleted.  While this is a net benefit, the cause of
this change is a Docker breakage (which arguably …
> *: various whiteout improvements

- cmd/umoci/main.go
We added a hint if a user got EPERM to use --rootless to try to fix it
in a9ebb42831ad ("cmd: give 'helpful' hint about --rootless"). However,
since then we changed the logging to be a bit less noisy and this patch
was lost in the changes -- so we need to make this a bit louder to make
sure it's visible by default.
Fixes #262 
Reported-by: Vincent Batts <vbatts@hashbangbash.com>
> umoci: make --rootless hint louder

- cmd/umoci/insert.go
- doc/man/umoci-raw-unpack.1.md
- doc/man/umoci-raw.1.md
- doc/man/umoci-stat.1.md
- doc/man/umoci-unpack.1.md
- doc/man/umoci.1.md
- doc/site/advanced/workflow-optimisation.md
- doc/site/quick-start/getting-an-image.md
- test/help.bats
- test/insert.bats
umoci-insert(1) is quite useful, and we should tell people about it in
our documentation (especially since the need for --opaque and --whiteout
require a bit of explanation and warning). I also noticed some of our
skopeo warnings are out-of-date and so I've removed them.
> doc: site: updates to include more information

- .travis.yml
- Dockerfile
Change golint path to fix Travis CI jobs. 
Like this: https://travis-ci.org/openSUSE/umoci/jobs/441992106 .
xref: https://github.com/golang/lint/issues/415
xref: https://github.com/golang/lint/issues/397
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
> fix go lint link

- cmd/umoci/utils_ux.go
9d126685960c ("oci: casext: extend scope of valid reference names")
added support for having ':' in reference names (in accordance with the
OCI specification updates), but unfortunately it missed that the primary
flag that interacts with reference names (--image) didn't support having
colons in the image tag.
Fixes #265
> umoci: allow ':' in --image (and similar flags)

- CHANGELOG.md
- cmd/umoci/config.go
- cmd/umoci/insert.go
- cmd/umoci/raw-add-layer.go
- cmd/umoci/repack.go
- cmd/umoci/utils_ux.go
- doc/man/umoci-config.1.md
- doc/man/umoci-insert.1.md
- doc/man/umoci-raw-add-layer.1.md
- doc/man/umoci-repack.1.md
- mutate/mutate.go
- mutate/mutate_test.go
- test/config.bats
- test/insert.bats
- test/repack.bats
Some users (like KIWI) want to end up with an image that only has a
single history entry for the one layer they have generated, but
umoci-config(1) normally generates a config entry for each invocation.
To allow for this usecase, a new --no-history flag was added which just
avoids adding the history in mutate/. Note that a warning will be
printed when using this flag with commands that add new layers because
layers-without-history-entries can cause lots of problems when looking
at the image information (especially if a later image is added with a
history entry -- the history entry will be incorrectly attributed to the
earlier layer).
> *: add --no-history to disable history auto-appending

- oci/layer/unpack.go
We have cases where we want to unpack layers over the top of some stuff
that we've already put on the disk. Add a flag to allow this.
> UnpackRootfs: allow unpacking over existing rootfs

- CHANGELOG.md
- cmd/umoci/insert.go
- cmd/umoci/utils_ux.go
- doc/man/umoci-config.1.md
- doc/man/umoci-insert.1.md
- test/insert.bats
Before this there was no way to make --tag non-destructive, so we just
copy the semantics from umoci-config. This won't break existing scripts
because the default is still to override (just like it is with
umoci-config).
> umoci: add --tag to umoci-insert

- oci/layer/tar_generate.go
- test/create.bats
Go 1.10's archive/tar decided to add Uname and Gname to archives by
default[1], which obviously is a bit of an issue for us if we want to be
reproducible across Go versoins. To counter-act this we explicitly set
them all to the zero value.
To avoid chasing shadows in the future, we'll add some regression tests
to make sure that Go's archive/tar doesn't regress us again.
Normally regression tests are for your own project, but (as seen
throughout umoci's history) we are currently acting as one of the few
regression tests of many other projects. In the past we've found plenty
of Go bugs and bugs in many other OCI tools, but this was usually due to
some pretty blatant problems.
Recently though there have been a slew of increasingly subtle Go
changes. Unfortunately it's not possible for us to …
> oci: handle Go 1.10 change to FileInfoHeader 

- go.sum
- vendor/github.com/rootless-containers/proto/go-proto/rootlesscontainers.proto
Without this patch, umoci fails to build from source with go 1.11.4.
go 1.11.4 fixes a bug where the checksums for certain types of go modules are incorrectly generated. As such, the go.sum file must be regenerated.
See the following for more information:
https://github.com/golang/go/issues/29278
https://github.com/golang/go/issues/29282
> Update gomodule checksums for go 1.11.4

- .gitignore
- .travis.yml
- Dockerfile
- Makefile
- cmd/umoci/main.go
- go.mod
- hack/test-vendor.sh
- mutate/mutate.go
- oci/cas/dir/dir.go
- oci/casext/blob.go
- oci/layer/generate.go
- oci/layer/tar_extract.go
- oci/layer/unpack.go
- oci/layer/utils.go
- pkg/unpriv/unpriv.go
- third_party/shared/util.go
- third_party/user/user.go
- utils.go
- vendor/modules.txt
It's necessary to add CI checks for gosec as well as `go mod vendor` sanity.
> ci: add more checks

- CHANGELOG.md
- Dockerfile
- cmd/umoci/raw-runtime-config.go
- cmd/umoci/raw-unpack.go
- cmd/umoci/unpack.go
- mutate/mutate.go
- oci/cas/dir/dir.go
- oci/casext/blob.go
- oci/casext/verified_blob.go
- oci/layer/unpack.go
- pkg/hardening/verified_reader.go
- pkg/hardening/verified_reader_test.go
- test/hardening.bats
- utils.go
Previously we didn't really check that blobs matched their hashes
directly -- most of the checks we did were based on layer DiffIDs and
similar checks.
Here we add a new casext.GetVerifiedBlob() API which wraps the
underlying reader with a VerifiedReadCloser that will verify that the
digest matches on EOF (or on Close). Users should be very careful to
ensure that they actually check all errors (such as when using
ioutil.Discard or when they do Close).
In addition, we add it to the underlying oci/cas/dir implementation
(just for safety). This adds effectively no overhead since
VerifiedReadCloser will not double-up on verification if the digest is
the same. We also add a basic verification of this as an integration and
some unit tests -- so that we can have some confidence it actually works …
> oci: cas*: add blob verification

- pkg/system/utime_linux.go
Use unix.AT_FDCWD and the absolute path for unix.UtimesNanoAt in order
to avoid having to open the parent directory on each call to Lutimes.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> pkg: system: use AT_FDCWD in UtimesNanoAt call

- .travis.yml
- test/config.bats
- test/create.bats
- test/gc.bats
- test/hardening.bats
- test/helpers.bash
- test/insert.bats
- test/pack_mapping.bats
- test/raw-add-layer.bats
- test/raw-config.bats
- test/raw-unpack.bats
- test/repack.bats
- test/stat.bats
- test/tag.bats
- test/unpack.bats
The code that used $BATS_TMPDIR was written before I noticed that it's
actually not a per-test random directory and is instead a way of
referencing /tmp. In particular, the use of $BATS_TMPDIR for $IMAGE was
a blocker for using the new parallel job support I'm working on adding
to bats.
In order to make this not too repetitive, I've created a new
$UMOCI_TMPDIR which is randomised for each test run.
> test: replace incorrect use of BATS_TMPDIR

- Dockerfile
- hack/test-integration.sh
- test/config.bats
- test/gc.bats
- test/helpers.bash
- test/raw-config.bats
There were a few changes to run() made in bats 1.0, and these broke some
incorrectly-written tests. Fixing this was mostly a few trivial cases of
using "@{foo[@]}" where we weren't previously.
Use the [*not-yet-merged* parallelism support I've been working on in
bats][1] in order to speed up our tests massively. This requires that we
use my home project on OBS, but hopefully my patches will be merged
eventually.
[1]: https://github.com/bats-core/bats-core/pull/172
> test: use bats --jobs support to speed up tests 

- Makefile
- hack/release.sh
In order to be able to handle projects where the version is generated
differently (such as autotools), and using Go for determining the
architecture makes no sense move the generation of those variables to
the user-configurable section.
> hack: release: make version and arch configurable

- CHANGELOG.md
- oci/layer/unpack.go
Due to an oversight in runc, setting a type other than "" or "bind" will
result in weird errors (especially when dealing with file-based
bind-mounts).
To get around this, we can simply set an empty type. This oversight is
being dealt with upstream, but won't help old runc releases (so we need
this workaround -- and we use "bind" to work with much older releases as
well).
Fixes: #294
> layer: specify "type: bind" in config.json for bind-mounts

- repack.go
- test/repack.bats
Here's some code to avoid inserting empty layers, and instead just creating a history entry to log that something happened.
> No empty layers

- oci/layer/tar_extract.go
This is a simple proposal to address #303 - I understand this may be naive / it may be that inability to deal with the `xattrs` is considered more than a warning.
Closes #303
If we are extracting to a filesystem that does not support xattrs, make
sure that an ENOTSUP from clearxattr or listxattr results in a warning,
not an error.
Signed-off-by: David Trudgian <dave@trudgian.net>
> tar_extract: don't error on fs without xattr support

- oci/layer/tar_extract.go
If there was an error in io.Copy() which resulted in a short write, we
used to hide the error (though the error would be quite useful for
debugging). Thus only set err to io.ErrShortWrite if there's no error
set already.
Fixes #301
Reported-by: Tycho Andersen <tycho@tycho.ws>
> tar_extract: don't mask original error on short write

- CHANGELOG.md
- oci/layer/tar_extract.go
When a destination filesystem does not support xattrs we are rasing at
least 1 ENOTSUP related warning per file. This is unhelpful, and can
scroll the terminal obscuring more important warnings. Instead, show a
single warning for the first occurrence, with an improved explanation of
the cause.
Signed-off-by: David Trudgian <dave@trudgian.net>
> tar_extract: only warn once about xattr ENOTSUP

- cmd/umoci/repack.go
- repack.go
Instead of just allowing for masking paths, let's allow for completely
custom filters in Repack().
> api: allow for custom filters in Repack()

- .travis.yml
- Makefile
It's a bit silly to build a Docker image just to run 'go-md2man'.
Fixes #319
> make: switch 'make docs' to always be a local build

- Dockerfile
- Makefile
- oci/layer/tar_extract_test.go
- pkg/unpriv/unpriv_test.go
- test/helpers.bash
- test/runc.bats
We've had cases where the default setup of "umoci + runc" didn't work
(usually in rootless container scenarios). Since this is a very common
usage of umoci, it makes sense to check it.
> test: add runc smoke-test

- oci/casext/gc.go
- oci/casext/gc_test.go
For our dist-spec implementation [1][2],
we have a use case where we use umoci's GC code to clean up orphaned
blobs. The issue is that as per dist-spec layer upload and manifest
updates are two different API calls and typically in that order, which
means layers begin life as orphans.
Adding the proposed patch allows us to:
a) mitigate the above issue
b) have a generic policy framework for future expansion
[1] https://github.com/opencontainers/distribution-spec
[2] https://github.com/anuvu/zot
> GC: add support for GC policies

- Dockerfile
There's no real point to use `home:cyphar:bats` now that 1.2.0 has been released.
> dockerfile: clean up build

- cmd/umoci/insert.go
- cmd/umoci/raw-add-layer.go
- mutate/mutate.go
- mutate/mutate_test.go
- repack.go
a couple of commits to allow introspection of mutator
> mutate: Add() should tell you what it added

- cmd/umoci/insert.go
- cmd/umoci/raw-add-layer.go
- mutate/compress.go
- mutate/compress_test.go
- mutate/mutate.go
- mutate/mutate_test.go
- repack.go
at least via the API for now :)
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
> mutate: allow for custom compression

- oci/layer/tar_generate.go
See comment for details; basically this is a during-image-build-time-only
thing.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
> layer: ignore overlay.impure xattr

- Makefile
- hack/ci-codecov.sh
- hack/test-integration.sh
- hack/test-unit.sh
We don't have any secrets in our CI, but it doesn't hurt to be sure now
that they actually publish hashes in a way that we can easily verify. We
can also pin the version (though in the future we should probably pull
the script from codecov.io and verify it using GitHub separately).
> ci: verify codecov hashes

- Dockerfile.fuzz
- test/fuzzing/README.md
This PR adds documentation on running the fuzzers locally. 
It adds the `/test/fuzzing` that holds the Dockerfile and the Readme.
> Add documentation for running fuzzers

- oci/cas/cas.go
- oci/cas/dir/dir.go
- oci/casext/walk.go
Since all of these blobs are not parseable, we won't be able to fetch
sub-descriptors from them, and thus there's no real point trying to
recurse into them. Before commit 4faf753 ("pkg: hardening: slurp
trailing bytes in VerifiedReadCloser.Close()") this wasn't too big of a
deal, but after that commit Close() is quite expensive for blobs you
don't use.
Reported-by: Tycho Andersen <tycho@tycho.pizza>
> oci: casext: walk: do not attempt to recurse into un-parseable blobs 

- .github/workflows/ci.yml
This allows us to switch away from our own codecov.sh wrapper
eventually, though we do still depend on the "env" tool. This also
allows us to migrate to the new codecov tool without having to do
anything particularly special.
Fixes #377
> ci: use codecov-action

- Makefile
which is not available in some build environments
> fix(Makefile): avoid usage of which

- .github/workflows/ci.yml
- mutate/mutate_fuzzer.go
- oci/casext/fuzzer.go
- oci/config/convert/utils_unix.go
- oci/layer/generate_linux_test.go
- oci/layer/layer_fuzzer.go
- oci/layer/tar_extract_linux_test.go
- pkg/hardening/fuzzer.go
- pkg/system/mknod_unix.go
- pkg/testutils/ftimes_unix.go
- pkg/testutils/mount_linux.go
- pkg/testutils/mount_unsupported.go
Go 1.17 adds the new "//go:build ..." style of build tags, and gofmt now
requires them to be used so add them -- CI is failing otherwise.
> *: use go1.17-friendly go:build tags

- .github/workflows/ci.yml
It seems GHA changed their default installed set of brew packages to no
longer include parallel, which causes the "brew unlink" command to fail.
So first check if parallel is installed.
> ci: osx: only try to unlink parallel if installed

- Dockerfile
- Makefile
- mutate/mutate.go
- mutate/mutate_fuzzer.go
- mutate/mutate_test.go
- new.go
- oci/cas/dir/dir.go
- oci/casext/gc_test.go
- oci/casext/map_test.go
- oci/casext/mediatype/parse.go
- oci/casext/refname_dir_test.go
- oci/layer/layer_fuzzer.go
- oci/layer/unpack_test.go
- test/create.bats
Ensure that we never permit an ambigous blob (one that can be either a
manifest or index) and make sure we set and check the now-defined
MediaType field whenever parsing such blobs.
> oci: protect against mediatype confusion attacks (CVE-2021-41190)

- Dockerfile.fuzz
Go is backwards compatible, so it makes more sense to just use the
latest version rather than pinning a version which we need to update
with dependabot regularly.
> fuzz: always use golang:latest

- cmd/umoci/insert.go
- cmd/umoci/raw-add-layer.go
- mutate/mutate.go
- mutate/mutate_test.go
- repack.go
We want to include some additional hash data in the annotations when
generating layers, so let's allow setting this.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>
> mutator: allow setting annotation data when generating a layer

- Dockerfile
All released versions of runtime-tool are not using go.mod, meaning that we end up pulling the latest version of their dependencies when using "go install". In particular, the runtime-spec update causes validation errors in our CI because we are still producing runtime-spec 1.0.2 config.jsons and runtime-tool doesn't support validating older versions.
> ci: avoid go install for github.com/opencontainers/runtime-tool

- pkg/unpriv/unpriv.go
If the inode is a mountpoint, chmod may just fail.
(See https://github.com/project-stacker/stacker/issues/450)
> Do not chmod +r if we don't need to

- oci/layer/tar_generate.go
If it's not supported, just assume there are no xattrs, don't fail the addfile.
> tarGenerator.AddFile: ignore llistxattr eopnotsupp

- .github/workflows/ci.yml
- Makefile
- hack/release.sh
For now, just build binaries for Linux. We do have integration tests for
MacOS/darwin, but I'm not sure if I'm comfortable saying we support
those architectures enough to release binaries for them.
Fixes #505
> release: build binaries for common architectures

- mutate/compress.go
- mutate/mutate.go
- mutate/mutate_test.go
- test/create.bats
Sometimes it is useful to have a reliable estimate of the space that would be taken up by a layer when it is unpacked. Since gzip's headers are only accurate up to 4GiB, larger layers can not be easily measured without uncompressing them.
This commit adds a field to the gzip and zstd compressors to store the bytes read from the stream during compression and uses that to set an annotation on newly generated layers.
If the noop compressor is used, the annotation is not added, as the existing "compressed" layer size would be the same.
👀 note that the annotation name is just a shot in the dark, I am open to suggestions for something that'd make more sense.
For validation, I unpacked the `opensuse/leap:15.4` image with `sudo ~/umoci/umoci unpack --image opensuse:latest opensuse-latest`
added a …
> mutate: add uncompressed blob size annotation

- Dockerfile
we are seeing:
2.947 go: github.com/opencontainers/image-tools/cmd/oci-image-tool imports
2.947 	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.9.3: parsing go.mod:
2.947 	module declares its path as: github.com/sirupsen/logrus
2.947 	        but was required as: github.com/Sirupsen/logrus
in CI, hopefully this replace fixes it?
> fix a Sirupsen/logrus import issue in CI

- oci/layer/generate.go
- test/helpers.bash
- test/insert.bats
This fixes #436.
I added a test that shows the issue - the commit with the fix has the full explanation, repeated here:
generatelayer closes the tarwriter, but generateinsertlayer forgets to.
Closing the tarwriter writes the required footer of 1k of zeros.
This results in tar files that are complete but invalid, and different
reading tools will behave differently:
- bsdtar doesn't complain and exits 0
- gnu tar (and security scanning tools that use it) will exit 2 with an
unexpected EOF message
- python's tarfile library will raise an Unexpected EOF error
- golang's archive/tar library can raise an unexpected EOF error, but
for some files created by generateinsertlayer, it just raises a
plain EOF error, which means golang based tools generally ignore this
and work fine, this includes …
> generateinsertlayer: ensure that we close the tarwriter

- .github/workflows/ci.yml
We need to upate upload- and download-artifact simultaneously. This should improve the speed of our CI jobs because we need to upload the generated Docker CI image during our CI.
> gha: update actions/*-artifact to v4

- doc/site/quick-start/rootless.md
Doc says `and` but I think it should be `an`?
> Fixed typo in rootless.md

- oci/casext/mediatype/parse.go
- oci/casext/refname_dir_test.go
We cannot use generics for the parser function map, but we can use it when instantiating "simple" JSON parser functions. There are a few other downsides to Go's generics, so this should just be a minor (possibly even theoretical) performance improvement over constructing the parsed types using reflection.
> oci: casext: mediatype: switch to generics for parser functions

- CHANGELOG.md
- pkg/idtools/idtools.go
This isn't a huge issue, but it could cause user confusion if they
provide too large a value.
> idtools: return errors for >u32 specification

- CHANGELOG.md
- oci/layer/generate.go
- oci/layer/generate_linux_test.go
- oci/layer/generate_test.go
- oci/layer/tar_extract.go
- oci/layer/tar_extract_linux_test.go
- oci/layer/tar_extract_test.go
- oci/layer/tar_generate.go
- oci/layer/tar_generate_test.go
- oci/layer/types.go
- oci/layer/utils.go
- oci/layer/utils_unix.go
- oci/layer/xattr.go
- oci/layer/xattr_linux_test.go
- oci/layer/xattr_test.go
- pkg/fseval/fseval.go
- pkg/fseval/fseval_default.go
- pkg/fseval/fseval_rootless.go
- pkg/pathtrie/trie.go
- pkg/pathtrie/trie_test.go
- pkg/system/xattr_unix.go
- pkg/system/xattr_unix_test.go
- pkg/unpriv/unpriv.go
- test/helpers.bash
It turns out that a lot of our overlayfs whiteout conversion code is actually quite broken, and quite a few things are not properly supported. Here are the set of issues we needed to fix:
- This is a reimplementation of #538 (which had several issues).
- We will probably need to switch `(*tarExtractor).upperPaths` to be a trie that will allow us to remove already-extracted regular whiteouts from a directory that then gets tagged as an opaque whiteout, as well as skip extracting regular whiteouts from a directory that is already and opaque whiteout. None of this is necessary for regular extractions but overlayfs kind of forces us to do this.
- :twisted_rightwards_arrows: `user.overlay.*` support feature moved to #576.
- Repacking a regular non-overlayfs layer with `trusted.overlay.*` will …
> layer: numerous overlayfs whiteout fixes

- CHANGELOG.md
- oci/layer/tar_extract.go
- oci/layer/tar_extract_linux_test.go
- oci/layer/tar_extract_test.go
(This depends on #587 being merged.)
Also fixes #546
> oci: layer: fix extraction with a non-directory parent component

- CHANGELOG.md
- oci/cas/dir/dir.go
- oci/casext/verified_blob.go
- oci/casext/verified_blob_test.go
- pkg/hardening/verified_reader.go
- pkg/hardening/verified_reader_test.go
VerifiedReadCloser previously would allow for negative ExpectedSize to
disable the size checking features added in commit ad66299 ("pkg:
hardening: expand to verify descriptor length").
This was based on a somewhat overly-permissive reading of the discussion
in opencontainers/image-spec#153 which was finally clarified in
opencontainers/image-spec#1285. Unknown sizes are a classic DoS vector,
so allowing them seems like a bad idea in general.
> pkg: hardening: disallow negative ExpectedSize

- internal/system/xattr_unix_test.go
- oci/layer/xattr_linux_test.go
Our tests would incorrectly treat security.selinux like a regular xattr,
which lead to failures because it gets auto-set on all new files. The
solution is quite simple -- just include any such xattrs in expected
sets (or filter them out) before doing checks in our tests.
umoci itself still handle security.selinux fine (we emulate it using a
fake user xattr), this is just a bug in our tests' handling of
security.selinux.
Fixes #605
Fixes: 6fd1e0e62645 ("oci: ignore system.nfs4_acl and extend forbidden-xattr handling")
Fixes: 9a1cefaf16bf ("oci: layer: correctly handle trusted.overlay xattr namespace escaping")
Fixes: 54f34c91a8f0 ("oci: layer: refix auto-applied xattr handling")
> tests: fix failures on SELinux-enabled systems

- CHANGELOG.md
- Dockerfile
- cmd/umoci/raw-mtree-validate.go
- cmd/umoci/raw.go
- cmd/umoci/utils_ux.go
- go.mod
- go.sum
- oci/layer/tar_generate.go
- test/helpers.bash
- test/raw-mtree-validate.bats
- test/raw-unpack.bats
- test/repack.bats
- test/unpack.bats
- vendor/github.com/vbatts/go-mtree/compare.go
- vendor/github.com/vbatts/go-mtree/entry.go
- vendor/github.com/vbatts/go-mtree/pkg/govis/README.md
- vendor/github.com/vbatts/go-mtree/pkg/govis/govis.go
- vendor/github.com/vbatts/go-mtree/pkg/govis/unvis.go
- vendor/github.com/vbatts/go-mtree/pkg/govis/vis.go
- vendor/modules.txt
The go-mtree CLI does not support rootless operations, which requires us
to use a patched version maintained in my OBS home project. This is a
little silly, and really we should just have a helper that calls
mtree.Check() with fseval.Rootless when in rootless mode.
At the moment, we only support the minimal set of flags needed for our
tests and the command is hidden from our help pages.
Closes #621
> umoci: add raw-mtree-validate helper to replace go-mtree

- .github/workflows/cflite-pr.yml
- .github/workflows/ci.yml
- Makefile
This lets us easily halve the execution time of CI runs and provides
more feedback about bugs that only affect rootful or rootless runs.
> gha: run rootless and rootful integration in parallel
